

services:
  influxdb:
    image: influxdb:2.7-alpine
    ports:
      - 8086:8086
    networks:
      - monitoring
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123 
      - DOCKER_INFLUXDB_INIT_ORG=performance-testing
      - DOCKER_INFLUXDB_INIT_BUCKET=jmeter-metrics
    volumes:
      - ./influx-db:/var/lib/influxdb2
    restart: unless-stopped

  grafana:
    image: grafana/grafana:main-ubuntu
    ports:
      - 3005:3000
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      - influxdb

networks:
  monitoring:
    driver: bridge
